---
- hosts: agent
  become: true
  become_user: edureka

  vars:
   ansible_become_pass: edureka
  tasks:
  - name: Install Git
    package:
     name: git
     state: present
  - name: Install docker.
    package:
      name: docker-ce
      state: present
  - name: Start docker service
    service:
      name: docker
      state: started
